apiVersion: v1                # Kubernetes API version used in this YAML decriptor (required field)
kind: Pod                     # Type of Kubernetes object/resource
metadata:                     # Pod metadata (name, labels, annotations and so on)
  name: nginx-pod             # Pod Name
spec:                         # Pod Specification/Contents (list of containers, volumes, image, ports and so on)
  containers:
  - image: nginx              # Container Image
    name: nginx-container     # Container Name
    ports:            
    - containerPort: 80       # The Port the container is listening on
      protocol: TCP