apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  namespace: application
  labels:
    tier: application
    app: apache
    release: stable
spec:
  containers:
  - name: apache
    image: paketobuildpacks/httpd:0.7
    ports:
    - containerPort: 80
 