apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  namespace: frontend
  labels:
    env: development
    tier: frontend
    app: wordpress
    release: stable
spec:
  containers:
  - image: wordpress:latest
    name: wordpress
    ports:
    - protocol: TCP
      containerPort: 80

