apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  namespace: frontend
  labels:
    env: development
    tier: frontend
    app: wordpress
    release: stable
spec:
  containers:
  - image: wordpress:latest
    name: wordpress
    ports:
    - protocol: TCP
      containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql.backend.svc.cluster.local
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_DB_PASSWORD
      value: mysecurepassword
    - name: WORDPRESS_DB_NAME
      value: wordpress


